### ISSUE TITLE
No way to contact owner of a workspace

### ISSUE THREAD

**Issue by seanhorgan** [DataBiosphere/terra-ui#1263]
When trying to access a workspace that I don't have access to, I get a message that doesn't help me move forward.

Can we do one of the following:
1. Display the owner's contact information
2. If the owner's contact info is considered sensitive, can we provide a mechanism for the requestor to request access through Terra and we pass along to the owner?
3. Provide a simple "contact us" action that enables the requestor to ask the Terra support team to make the request on their behalf.

![Screen Shot 2019-03-07 at 4.13.59 PM.png](https://images.zenhubusercontent.com/5a9878524b5806bc2bc909f7/2c76d709-e21a-4a93-a3ef-3179c95fc708)

**Comment by katevoss** [comment]
Will this be resolved by #1485 @breilly2 ? Or will a user still see this message if they try to access a workspace for which they don't have access?

**Comment by breilly2** [comment]
Not quite. This is what we display when we get a 404 from Rawls. If we can detect that the workspace has been shared with the user but they're not fully in the auth domain then we can provide a way to request access like #1485 (which is focused on the workspace list). Otherwise, we long ago decided to be intentionally vague about this... treating "not discoverable" as "does not exist" from the user's point of view.

**Comment by kleighwe** [comment]
Invalid. Product works as designed, users should now be prevented from getting into this scenario in the first place.
