### ISSUE TITLE
Requesting Access to authorization domains

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1485]
When you open a link to a workspace protected by an Authorization domain composed of one or more groups to which you do not belong, we should present you with the following text, and a button to request access to each group on the auth domain:
<img width="847" alt="Screen Shot 2019-04-29 at 2 06 42 PM" src="https://user-images.githubusercontent.com/3492466/56916923-2330ad80-6a88-11e9-94ba-a46eaf9e336e.png">

When searching in the workspace list, FireCloud presents this as a modal over the workspace list, which is nice because you don't lose your search context. We should do that.

When navigating to a page directly from a link, FireCloud simply says "not found". We should show a blank screen with the modal above it.

Request access behavior should be the same as FireCloud. Confirm this with Cloud Accounts- I believe it sends an email to the group's admins. We should ask cloud accounts to update this email to a Terra branded email if not done already

Dependencies
* checking with Cloud Accounts about email behavior (not blocking)
* checking with Cloud Accounts about email branding (not blocking)

Open Questions
What does the UI do when the "Request Access" button is clicked.

Any hard Deadlines?
Soft deadline end of May

Is this noteworthy? Does Comms need to know? 
Should go in release notes. No separate product announcement.

**Comment by breilly2** [comment]
In most cases, the "Request Access" button emails the managed group admins with the request for the user to be added.* There are some special cases where some instructions are (supposed to be) displayed instead, specifically "TCGA-dbGaP-Authorized" and "TARGET-dbGaP-Authorized". However, somewhere along the line, 2 things happened:

* The data for these instructions went missing (both dev and prod, probably other envs as well): https://broadworkbench.atlassian.net/browse/CA-274
* The Sam endpoint for setting these instructions stopped working: https://broadworkbench.atlassian.net/browse/CA-260

Until at least one of these issues is resolved, we won't be able to implement/test the code for that part of this feature.

While this only affects a couple of groups, I would guess that it affects a significant percentage of the auth-domain of workspaces in production. @bradtaylor, do you want to release this in two stages or wait until the special access instruction issues are fixed?

\* We do not keep track of these requests, so the UI cannot show whether or not a request has been sent if the modal is closed and re-opened.

**Comment by melissachang** [comment]
FYI this would be useful for my Data Explorer work, but with one non-urgent addition.

*Background*

NHS DE is protected by nhs_saturn_users auth domain.

Currently, if you click Browse Data button for NHS DE, the DE opens in a new tab. If you aren't in auth domain, you see a Google account switcher.

I'm working on embedding DE instead of opening a new tab. With embedded DE, if you click Browse Data and aren't in auth domain, you just see a blank page:

![1](https://user-images.githubusercontent.com/10929390/57955621-3676b200-78ab-11e9-8e24-81893050afed.png)

(This is due to limitations around Identity-Aware Proxy and iframes.)

So I will determine if user is in NHS auth domain and *only* show DE if user is in auth domain.

If user is not in auth domain, I'd like to show the above Request Access modal.

*Requested addition*

I'd like to add text like "Or switch to an account that is part of the group".

For example, I mainly use Terra as `melchang@g**.com`. NHS data can only be accessed with a channing Google account. So if I'm logged in as `melchang@g**.com` and click "Browse data", it would be nice if I got a reminder to switch to my channing account.
