### ISSUE TITLE
WRITER cannot promote READER without re-adding them

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/terra-ui#1524]
A WRITER (with can share) should be able to promote a READER to a WRITER, without having to remove and re-add them to the list. They should be able to Edit their permissions.

WARNING: This is a Heisenbug, carefully check that this is actually a bug first.

**Comment by kleighwe** [comment]
@elizzhao can you toss an estimate on this when you get a chance?

**Comment by elizzhao** [comment]
So upon exploring this ticket, I found that as a a writer, you can't edit user's permissions directly with the dropdown (rawls throws an error that you don't have the correct permissions since they specify that only owners can edit). I've been able to sometimes remove and add users with different permissions, but other times I get the same permission error. In general, there was still some inconsistency while I was trying to methodically test out the behavior, but this seemed to be the general pattern. 

We'd like writers with share permissions to be able to edit instead of throwing an error. 

In any case, this seems to be an issue with rawls, and it's not clear to us what should/shouldn't be allowed (and thus how we should change our UI to reflect that), so I'm moving this ticket to blocked on cloud accounts, and filing a ticket on their end.

**Comment by elizzhao** [comment]
Upon further thought, I'm going to close this ticket because there isn't any work to be done on our end for this specifically yet. If there is, it should be reflected elsewhere. 

Corresponding ticket in cloud accounts filed from investigation of this ticket: https://broadworkbench.atlassian.net/secure/RapidBoard.jspa?rapidView=12&projectKey=CA&view=planning&selectedIssue=CA-242
