### ISSUE TITLE
3 node cluster being created instead of a single notebook VM

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/terra-ui#1550]
I created a new notebook VM in a new Terra project and when I look at the instances list in the Cloud console, I see 3 VMs created:

- saturn-616cedf5-cd3d-4dee-a860-be597706708f-m
- saturn-616cedf5-cd3d-4dee-a860-be597706708f-w-0
- saturn-616cedf5-cd3d-4dee-a860-be597706708f-w-1

`Configure as Spark cluster` is NOT checked.

A co-worker also created a notebook runtime and we observe 3 VMs created.

**Comment by rtitle** [comment]
Hi @mbookman,

I looked at this and unfortunately I think it's a Leo bug. :-( A change released last week allowed for user-specified Spark properties. Unfortunately I think it was overwriting the `dataproc:dataproc.allow.zero.workers` property which is needed for 0-worker clusters. I made a PR (https://github.com/DataBiosphere/leonardo/pull/907) to fix this. We'll get it release ASAP next week.

**Comment by rtitle** [comment]
@mbookman the fix is live in prod as of 5/5 2:30pm EST. I made a cluster in Terra and verified I get only 1 instance as expected:

![image](https://user-images.githubusercontent.com/5368863/57198500-92ebe000-6f41-11e9-8cd7-9b5d8efec0cf.png)

The dataproc properties are set as expected too. 

So you should be free to recreate clusters. We'll follow up with a post mortem as mentioned via email.
